document.write( '<ul class=\"bxslider - feature - product \">\n' );
document.write( '\n' );
document.write( '    <li class=\"item\">\n' );
document.write( '\n' );
document.write( '        <div class=\"product-item\">\n' );
document.write( '            <p class=\"product-image\">\n' );
document.write( '                <a href=\"http://www.ebay.com.au/itm/Grey-Oak-12mm-Premium-Laminate-Flooring-Floating-Floor-Greyish-Timber-Look-DIY-/152505113867?hash=item2382035d0b\" title=\"Grey Oak 12mm Premium Laminate Flooring/ Floating Floor Greyish Timber Look DI \"><img class=\"lazy-image\" data-original=\"http://www.lionkingflooring.com.au/ebay/images/trending/t2.jpg\" alt=\"\" src=\"http://www.lionkingflooring.com.au/ebay/images/trending/t2.jpg\" style=\"display: inline-block;\">\n' );
document.write( '                </a>\n' );
document.write( '            </p>\n' );
document.write( '\n' );
document.write( '            <p class=\"product-name\">\n' );
document.write( '                <a href=\"http://www.ebay.com.au/itm/Grey-Oak-12mm-Premium-Laminate-Flooring-Floating-Floor-Greyish-Timber-Look-DIY-/152505113867?hash=item2382035d0b\" title=\"Grey Oak 12mm Premium Laminate Flooring/ Floating Floor Greyish Timber Look DI \">Grey Oak 12mm Premium Laminate Flooring/ Floating Floor Greyish Timber Look DI</a>\n' );
document.write( '            </p>\n' );
document.write( '            <div class=\"product-price\">\n' );
document.write( '                <span class=\"price\">AU $19.99</span>\n' );
document.write( '            </div>\n' );
document.write( '            <div style=\"display: none;\" class=\"view-details\">\n' );
document.write( '                <a href=\"http://www.ebay.com.au/itm/Grey-Oak-12mm-Premium-Laminate-Flooring-Floating-Floor-Greyish-Timber-Look-DIY-/152505113867?hash=item2382035d0b\" title=\"View Details\" target=\"_blank\">\n' );
document.write( '                    <span>View Details</span>\n' );
document.write( '                </a>\n' );
document.write( '            </div>\n' );
document.write( '            <div style=\"display: none;\" class=\"buy-now\">\n' );
document.write( '                <a href=\"http://www.ebay.com.au/itm/Grey-Oak-12mm-Premium-Laminate-Flooring-Floating-Floor-Greyish-Timber-Look-DIY-/152505113867?hash=item2382035d0b\" title=\"Buy Now\">Buy Now</a>\n' );
document.write( '            </div>\n' );
document.write( '        </div>\n' );
document.write( '    </li>\n' );
document.write( '\n' );
document.write( '    <li class=\"item\" style=\"float: left; list-style: none; position: relative; width: 180px; margin-right: 55px;\">\n' );
document.write( '        <div class=\"product-item\">\n' );
document.write( '            <p class=\"product-image\">\n' );
document.write( '                <a href=\"http://www.ebay.com.au/itm/Grey-WPC-Outdoor-Decking-Bamboo-Plastic-Composite-Decks-Decking-Pergolas-Timber-/151472267051?hash=item2344735f2b\" title=\"Grey WPC Outdoor Decking Bamboo Plastic Composite Decks Decking Pergolas Timber\"><img class=\"lazy-image\" data-original=\"http://www.lionkingflooring.com.au/ebay/images/trending/t3.jpg\" alt=\"\" src=\"http://www.lionkingflooring.com.au/ebay/images/trending/t3.jpg\" style=\"display: inline-block;\">\n' );
document.write( '                </a>\n' );
document.write( '\n' );
document.write( '            </p>\n' );
document.write( '\n' );
document.write( '            <p class=\"product-name\"><a href=\"http://www.ebay.com.au/itm/Grey-WPC-Outdoor-Decking-Bamboo-Plastic-Composite-Decks-Decking-Pergolas-Timber-/151472267051?hash=item2344735f2b\" title=\"Grey WPC Outdoor Decking Bamboo Plastic Composite Decks Decking Pergolas Timber\">Grey WPC Outdoor Decking Bamboo Plastic Composite Decks Decking Pergolas Timber</a>\n' );
document.write( '            </p>\n' );
document.write( '            <div class=\"product-price\">\n' );
document.write( '                <span class=\"price\">AU $51.80</span>\n' );
document.write( '            </div>\n' );
document.write( '            <div style=\"display: none;\" class=\"view-details\">\n' );
document.write( '                <a href=\"http://www.ebay.com.au/itm/Grey-WPC-Outdoor-Decking-Bamboo-Plastic-Composite-Decks-Decking-Pergolas-Timber-/151472267051?hash=item2344735f2b\" title=\"View Details\" target=\"_blank\">\n' );
document.write( '                    <span>View Details</span>\n' );
document.write( '                </a>\n' );
document.write( '            </div>\n' );
document.write( '            <div style=\"display: none;\" class=\"buy-now\">\n' );
document.write( '                <a href=\"http://www.ebay.com.au/itm/Grey-WPC-Outdoor-Decking-Bamboo-Plastic-Composite-Decks-Decking-Pergolas-Timber-/151472267051?hash=item2344735f2b\" title=\"Buy Now\">Buy Now</a>\n' );
document.write( '            </div>\n' );
document.write( '        </div>\n' );
document.write( '    </li>\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '    <li class=\"item\" style=\"float: left; list-style: none; position: relative; width: 180px; margin-right: 55px;\">\n' );
document.write( '        <div class=\"product-item\">\n' );
document.write( '            <p class=\"product-image\">\n' );
document.write( '                <a href=\"http://www.ebay.com.au/itm/12mm-Laminate-Flooring-Floating-Floor-Timber-Click-Lock-Floorboards-Sample-Pack-/401397487518?hash=item5d7527979e\" title=\"12mm Laminate Flooring Floating Floor Timber Click Lock Floorboards\"><img class=\"lazy-image\" data-original=\"http://www.lionkingflooring.com.au/ebay/images/trending/t1.jpg\" alt=\"\" src=\"http://www.lionkingflooring.com.au/ebay/images/trending/t1.jpg\" style=\"display: inline-block;\">\n' );
document.write( '                </a>\n' );
document.write( '\n' );
document.write( '            </p>\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '            <p class=\"product-name\"><a href=\"http://www.ebay.com.au/itm/12mm-Laminate-Flooring-Floating-Floor-Timber-Click-Lock-Floorboards-Sample-Pack-/401397487518?hash=item5d7527979e\" title=\"12mm Laminate Flooring Floating Floor Timber Click Lock Floorboards\">12mm Laminate Flooring Floating Floor Timber Click Lock Floorboards</a>\n' );
document.write( '            </p>\n' );
document.write( '            <div class=\"product-price\">\n' );
document.write( '                <span class=\"price\">AU $19.99</span>\n' );
document.write( '            </div>\n' );
document.write( '            <div style=\"display: none;\" class=\"view-details\">\n' );
document.write( '                <a href=\"http://www.ebay.com.au/itm/12mm-Laminate-Flooring-Floating-Floor-Timber-Click-Lock-Floorboards-Sample-Pack-/401397487518?hash=item5d7527979e\" title=\"View Details\" target=\"_blank\">\n' );
document.write( '                    <span>View Details</span>\n' );
document.write( '                </a>\n' );
document.write( '            </div>\n' );
document.write( '            <div style=\"display: none;\" class=\"buy-now\">\n' );
document.write( '                <a href=\"http://www.ebay.com.au/itm/12mm-Laminate-Flooring-Floating-Floor-Timber-Click-Lock-Floorboards-Sample-Pack-/401397487518?hash=item5d7527979e\" title=\"Buy Now\">Buy Now</a>\n' );
document.write( '            </div>\n' );
document.write( '        </div>\n' );
document.write( '    </li>\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '    <li class=\"item\" style=\"float: left; list-style: none; position: relative; width: 180px; margin-right: 55px;\">\n' );
document.write( '        <div class=\"product-item\">\n' );
document.write( '            <p class=\"product-image\">\n' );
document.write( '                <a href=\"http://www.ebay.com.au/itm/12mm-Premium-Laminate-Flooring-Planks-Floating-Floors-Rustic-Oak-2-Strip-/152327086765?hash=item237766e2a\" title=\"12mm Premium Laminate Flooring Planks/ Floating Floors - Rustic Oak(2 Str\"><img class=\"lazy-image\" data-original=\"http://www.lionkingflooring.com.au/ebay/images/trending/t8.jpg\" alt=\"\" src=\"http://www.lionkingflooring.com.au/ebay/images/trending/t8.jpg\" style=\"display: inline-block;\">\n' );
document.write( '                </a>\n' );
document.write( '            </p>\n' );
document.write( '\n' );
document.write( '            <p class=\"product-name\"><a href=\"http://www.ebay.com.au/itm/12mm-Premium-Laminate-Flooring-Planks-Floating-Floors-Rustic-Oak-2-Strip-/152327086765?hash=item237766e2a\" title=\"12mm Premium Laminate Flooring Planks/ Floating Floors - Rustic Oak(2 Str\">12mm Premium Laminate Flooring Planks/ Floating Floors - Rustic Oak(2 Str.</a>\n' );
document.write( '            </p>\n' );
document.write( '            <div class=\"product-price\">\n' );
document.write( '                <span class=\"price\">AU $19.99</span>\n' );
document.write( '            </div>\n' );
document.write( '            <div style=\"display: none;\" class=\"view-details\">\n' );
document.write( '                <a href=\"http://www.ebay.com.au/itm/12mm-Premium-Laminate-Flooring-Planks-Floating-Floors-Rustic-Oak-2-Strip-/152327086765?hash=item237766e2a\" title=\"View Details\" target=\"_blank\">\n' );
document.write( '                    <span>View Details</span>\n' );
document.write( '                </a>\n' );
document.write( '            </div>\n' );
document.write( '            <div style=\"display: none;\" class=\"buy-now\">\n' );
document.write( '                <a href=\"http://www.ebay.com.au/itm/12mm-Premium-Laminate-Flooring-Planks-Floating-Floors-Rustic-Oak-2-Strip-/152327086765?hash=item237766e2a\" title=\"Buy Now\">Buy Now</a>\n' );
document.write( '            </div>\n' );
document.write( '        </div>\n' );
document.write( '    </li>\n' );
document.write( '</ul>' );
